# Generated by Django 4.2.16 on 2024-09-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_average_rating_recipe_cooking_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
